inc =  -lm 

problem1: problem1.cpp
	g++ -w -o problem1 problem1.cpp -Wno-deprecated -I ${inc}

problem3: problem3.cpp
	g++ -w -o problem3 problem3.cpp -Wno-deprecated -I ${inc}

problem5: problem5.cpp
	g++ -w -o problem5 problem5.cpp -Wno-deprecated -I ${inc}

clean:
	rm -f problem0 problem1 problem2 problem3 problem4